title: Beacoworks Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://status.beacoworks.xyz/'
params:
  alwaysKeepBrandColor: true
  autoRefresh: true
  brand: 0a0c0f
  customTabs: []
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: cc4400
  down: e60000
  googleAnalytics: UA-00000000-1
  incidentPostsPerPage: 10
  logo: /logo.png
  notice: 24478f
  ok: 008000
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: Main server on Vultr
      name: Speicher
    - description: Cloud Storage and Chat Server
      name: Sanctuary
    - description: '[数据删除]'
      name: tRna
    - description: '[数据删除]'
      name: Camellia
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
